kind: PersistentVolume
apiVersion: v1
metadata:
  name: cam-bpd-appdata-pv
  labels:
    type: cam-bpd-appdata
spec:
  capacity:
    storage: 20Gi
  accessModes:
     - ReadWriteMany
  nfs:
    server: mycluster.icp
    path: /export/CAM_BPD_appdata