kind: PersistentVolume
apiVersion: v1
metadata:
  name: cam-mongo-pv
  labels:
    type: cam-mongo
spec:
  capacity:
    storage: 15Gi
  accessModes:
     - ReadWriteMany
  nfs:
    server: mycluster.icp
    path: /export/CAM_db