kind: PersistentVolume
apiVersion: v1
metadata:
   name: cam-terraform-pv
   labels:
     type: cam-terraform
spec:
  capacity:
     storage: 15Gi
  accessModes:
     - ReadWriteMany
  nfs:
    server: mycluster.icp
    path: /export/CAM_terraform